language:
  python

python:
  - 3.6

install:
  - pip install -r requirements.txt

script:
- pytest src/tests/integration -v
- pytest src/tests/unit -v

notifications:
  email:
    recipients:
      - elia.vanwolputte@gmail.com
    on_success: change  # default: change
    on_failure: always  # default: always
