language:
  python

python:
  - 3.6

install:
  - pip install -r requirements.txt

script:
- pytest src/tests/integration

notifications:
  email:
    recipients:
      - elia.vanwolputte@gmail.com
    on_success: never # default: change
    on_failure: always # default: always
